
  name: puppetry
  version: '1.0.0'
  summary: Puppetry - codeless end-to-end test automation, integrated with CI/CD pipeline
  description: |
    Puppetry is an open-source scriptless test automation tool built on top of Google’s Puppeteer. It can be used by QA engineers with no programming background. Puppetry can also export the tests into a Jest.js project that can be  included into CI/CD pipeline.
  type: app
  icon: app/assets/256x256.png

  grade: stable
  confinement: classic

  apps:
    puppetry:
      command: desktop-launch $SNAP/puppetry/puppetry

  parts:
    src:
      source: .
      plugin: nodejs
      node-engine: 11.0.0
      build-packages:
        - python
        - libgtk2.0-0
        - libxtst-dev
        - libxss-dev
        - libgconf2-dev
        - libnss3

      after:
        - desktop-gtk2

      build: |
        npm run build &&
        node_modules/.bin/build --linux snap
      install: |
        mkdir $SNAPCRAFT_PART_INSTALL/puppetry
        cp -v -r dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/puppetry

